# Generated by Django 5.2.15 on 2026-09-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='function',
            field=models.CharField(blank=True, choices=[('secretary', 'Secrétaire'), ('coordinator', 'Coordonnateur'), ('treasurer', 'Trésorier')], max_length=20, verbose_name='Fonction dans l’extension'),
        ),
    ]
