# Generated by Django 5.2.15 on 2026-09-27 19:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0004_currency_remove_churchextension_currency_symbol_and_more'),
        ('reports', '0008_report_income_lines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=30)),
                ('fund', models.CharField(choices=[('tithe', 'Dîmes des dîmes'), ('social', 'Social'), ('extension', 'Caisse de l’extension'), ('pastor', 'Caisse du pasteur'), ('beneficiary', 'Bénéficiaires')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiary', models.CharField(blank=True, max_length=160, verbose_name='Bénéficiaire')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churches.currency')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churches.churchextension', verbose_name='Extension')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='reports.servicereport')),
            ],
            options={
                'ordering': ['-report__service_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('target', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='churches.churchextension')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Nom du département')),
                ('name_key', models.CharField(editable=False, max_length=160)),
                ('is_active', models.BooleanField(default=True, verbose_name='Département actif')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churches.churchextension', verbose_name='Extension')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regular_tithe', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Offrandes ordinaires — dîme (%)')),
                ('regular_social', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Offrandes ordinaires — social (%)')),
                ('tithe_tithe', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Dîmes reçues — dîme des dîmes (%)')),
                ('tithe_social', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Dîmes reçues — social (%)')),
                ('thanks_tithe', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Actions de grâce — dîme (%)')),
                ('thanks_social', models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Actions de grâce — social (%)')),
                ('extension', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='churches.churchextension', verbose_name='Extension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de remise')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant remis')),
                ('beneficiary', models.CharField(max_length=160, verbose_name='Bénéficiaire')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Référence / justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(editable=False, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ministry.allocation')),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_remittances', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160, verbose_name='Nom complet')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Fiche active')),
                ('is_worker', models.BooleanField(default=False, verbose_name='Ouvrier')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('widowed', 'Veuf/veuve'), ('divorced', 'Divorcé(e)')], max_length=20, verbose_name='État civil')),
                ('service_start', models.DateField(blank=True, null=True, verbose_name='Entrée en service')),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=160)),
                ('phone_key', models.CharField(blank=True, db_index=True, editable=False, max_length=60)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churches.churchextension', verbose_name='Extension')),
            ],
            options={
                'ordering': ['full_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('owner', models.CharField(max_length=160, verbose_name='Responsable')),
                ('status', models.CharField(choices=[('pending', 'À contacter'), ('contacted', 'Contacté'), ('accompanied', 'Accompagné')], max_length=20, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Note de suivi')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churches.churchextension', verbose_name='Extension')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='ministry.person')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('member', 'Membre'), ('head', 'Chef'), ('deputy', 'Chef adjoint')], max_length=12, verbose_name='Rôle')),
                ('start', models.DateField(default=django.utils.timezone.localdate, verbose_name='Début')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churches.churchextension', verbose_name='Extension')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='ministry.department', verbose_name='Département')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='ministry.person', verbose_name='Ouvrier')),
            ],
        ),
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('visit', 'Nouveau venu'), ('conversion', 'Âme gagnée')], max_length=12, verbose_name='Catégorie')),
                ('date', models.DateField(verbose_name='Date de l’événement')),
                ('invited_by', models.CharField(blank=True, max_length=160, verbose_name='Invité par')),
                ('follow_up_owner', models.CharField(blank=True, max_length=160, verbose_name='Responsable de suivi')),
                ('source', models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True)),
                ('date_inferred', models.BooleanField(default=False, verbose_name='Date reprise du culte, à vérifier')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churches.churchextension', verbose_name='Extension')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ministry.person')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.servicereport')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('report', 'category', 'fund'), name='unique_report_fund_allocation'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('extension', 'name_key'), name='department_name_per_extension'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end__isnull', True)), fields=('person', 'department'), name='one_active_department_assignment'),
        ),
        migrations.AddConstraint(
            model_name='personevent',
            constraint=models.UniqueConstraint(fields=('person', 'kind'), name='one_initial_event_per_person'),
        ),
    ]
