# Generated by Django 5.2.15 on 2026-09-27 20:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0004_currency_remove_churchextension_currency_symbol_and_more'),
        ('ministry', '0002_import_existing_people'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='churches.currency', verbose_name='Devise remise'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=12, default=1, editable=False, max_digits=24),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='person',
            name='merged_into',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='ministry.person'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_remittances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BeneficiaryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary', models.CharField(max_length=160, verbose_name='Bénéficiaire')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Part à remettre')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='ministry.allocation')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ministry.beneficiaryshare', verbose_name='Part du bénéficiaire'),
        ),
        migrations.AddConstraint(
            model_name='beneficiaryshare',
            constraint=models.UniqueConstraint(fields=('allocation', 'beneficiary'), name='unique_allocation_beneficiary'),
        ),
    ]
