# Generated by Django 5.2.15 on 2026-09-28 04:28

import uuid
from django.db import migrations, models


def populate_keys(apps, schema_editor):
    Payment = apps.get_model('ministry', 'Payment')
    for pk in Payment.objects.using(schema_editor.connection.alias).values_list('pk', flat=True).iterator():
        Payment.objects.using(schema_editor.connection.alias).filter(pk=pk).update(submission_key=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_payment_currency_payment_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='submission_key',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(populate_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment', name='submission_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
