# Generated by Django 5.2.15 on 2026-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appsetting",
            options={
                "verbose_name": "Paramètres généraux",
                "verbose_name_plural": "Paramètres généraux",
            },
        ),
        migrations.AlterModelOptions(
            name="churchextension",
            options={
                "ordering": ["name"],
                "verbose_name": "Extension",
                "verbose_name_plural": "Extensions",
            },
        ),
        migrations.AddField(
            model_name="churchextension",
            name="exchange_rate_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Taux mis à jour le"
            ),
        ),
        migrations.AddField(
            model_name="churchextension",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Logo officiel"
            ),
        ),
        migrations.AddField(
            model_name="churchextension",
            name="usd_exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="1 unité de la devise locale équivaut à X dollars USD",
                max_digits=14,
                verbose_name="Taux de change (→ USD)",
            ),
        ),
        migrations.AlterField(
            model_name="appsetting",
            name="church_name",
            field=models.CharField(
                default="Emerge in Christ",
                max_length=160,
                verbose_name="Nom de la communauté",
            ),
        ),
        migrations.AlterField(
            model_name="appsetting",
            name="social_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                max_digits=5,
                verbose_name="Pourcentage fonds social (%)",
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="color",
            field=models.CharField(
                default="#166534", max_length=7, verbose_name="Couleur"
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="coordinator",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Coordinateur"
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="country",
            field=models.CharField(blank=True, max_length=120, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="created_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fondation"
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="currency",
            field=models.CharField(
                default="EUR", max_length=8, verbose_name="Code devise"
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="currency_symbol",
            field=models.CharField(
                default="€", max_length=8, verbose_name="Symbole devise"
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="name",
            field=models.CharField(max_length=160, verbose_name="Nom de l'extension"),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="pastor_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email du pasteur"
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="pastor_name",
            field=models.CharField(blank=True, max_length=160, verbose_name="Pasteur"),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="pastor_phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Téléphone du pasteur"
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="secretary",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Secrétaire"
            ),
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="treasurer",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Trésorier"
            ),
        ),
    ]
