# Generated by Django 5.2.17 on 2026-09-14 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='social_percentage',
            field=models.DecimalField(decimal_places=2, default=5, help_text='De 0 à 90 %, en complément de la dîme de 10 %.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddConstraint(
            model_name='appsetting',
            constraint=models.CheckConstraint(condition=models.Q(('social_percentage__gte', 0), ('social_percentage__lte', 90)), name='social_percentage_valid'),
        ),
    ]
