# Generated by Django 5.2.15 on 2026-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churches", "0002_alter_appsetting_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchextension",
            name="social_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Pourcentage prélevé pour le fonds social sur les offrandes ordinaires, dîmes et actions de grâce.",
                max_digits=5,
                verbose_name="Pourcentage fonds social (%)",
            ),
        ),
        migrations.AddField(
            model_name="churchextension",
            name="tithe_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Pourcentage prélevé à titre de dîme sur les offrandes ordinaires, dîmes et actions de grâce.",
                max_digits=5,
                verbose_name="Pourcentage dîme (%)",
            ),
        ),
    ]
