# Generated by Django 5.2.15 on 2026-06-25 11:25

import django.db.models.deletion
from django.db import migrations, models


def initialize_currencies(apps, schema_editor):
    """Initialise les devises prédéfinies."""
    Currency = apps.get_model('churches', 'Currency')
    
    currencies_data = [
        {"code": "USD", "name": "Dollar américain", "symbol": "$", "usd_rate": 1.0, "is_default": True},
        {"code": "EUR", "name": "Euro", "symbol": "€", "usd_rate": 1.08},
        {"code": "TRY", "name": "Livre turque", "symbol": "₺", "usd_rate": 0.031},
        {"code": "CDF", "name": "Franc congolais", "symbol": "FC", "usd_rate": 0.00037},
        {"code": "GBP", "name": "Livre sterling", "symbol": "£", "usd_rate": 1.27},
        {"code": "XAF", "name": "Franc CFA (Afrique centrale)", "symbol": "FCFA", "usd_rate": 0.0016},
    ]
    
    for data in currencies_data:
        Currency.objects.get_or_create(
            code=data["code"],
            defaults=data
        )


def backup_legacy_data(apps, schema_editor):
    """Sauvegarde les données existantes dans les champs legacy."""
    ChurchExtension = apps.get_model('churches', 'ChurchExtension')
    
    for ext in ChurchExtension.objects.all():
        # Sauvegarder les anciennes valeurs dans les champs legacy
        if hasattr(ext, 'currency') and ext.currency and isinstance(ext.currency, str):
            ext.currency_code_legacy = ext.currency
        if hasattr(ext, 'currency_symbol'):
            ext.currency_symbol_legacy = ext.currency_symbol or "$"
        if hasattr(ext, 'usd_exchange_rate'):
            ext.usd_exchange_rate_legacy = ext.usd_exchange_rate or 1
        
        ext.save(update_fields=['currency_code_legacy', 'currency_symbol_legacy', 'usd_exchange_rate_legacy'])


def clear_currency_field(apps, schema_editor):
    """Met le champ currency à NULL avant la transformation en ForeignKey."""
    # Utiliser SQL direct pour contourner la contrainte NOT NULL
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute('UPDATE churches_churchextension SET currency = NULL')
    else:
        ChurchExtension = apps.get_model('churches', 'ChurchExtension')
        for ext in ChurchExtension.objects.all():
            ext.currency = None
            ext.save(update_fields=['currency'])


def restore_currency_foreign_key(apps, schema_editor):
    """Restaure les devises avec les ForeignKey après l'AlterField."""
    ChurchExtension = apps.get_model('churches', 'ChurchExtension')
    Currency = apps.get_model('churches', 'Currency')
    
    for ext in ChurchExtension.objects.all():
        # Trouver la devise correspondante depuis le champ legacy
        currency_code = ext.currency_code_legacy
        if currency_code:
            currency = Currency.objects.filter(code=currency_code).first()
            if currency:
                ext.currency = currency
            else:
                # Fallback: utiliser USD si la devise n'existe pas
                ext.currency = Currency.objects.filter(code="USD").first()
        else:
            # Fallback: utiliser USD
            ext.currency = Currency.objects.filter(code="USD").first()
        
        ext.save(update_fields=['currency'])


class Migration(migrations.Migration):
    dependencies = [
        ("churches", "0003_churchextension_social_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Code ISO (ex: USD)"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nom de la devise"),
                ),
                (
                    "symbol",
                    models.CharField(max_length=5, verbose_name="Symbole (ex: $)"),
                ),
                (
                    "usd_rate",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="1 unité de cette devise équivaut à X dollars USD",
                        max_digits=14,
                        verbose_name="Taux vers USD",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Devise par défaut (Admin)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Devise",
                "verbose_name_plural": "Devises",
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(initialize_currencies, migrations.RunPython.noop),
        migrations.AddField(
            model_name="churchextension",
            name="currency_code_legacy",
            field=models.CharField(
                default="EUR", max_length=8, verbose_name="Code devise (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="churchextension",
            name="currency_symbol_legacy",
            field=models.CharField(
                default="€", max_length=8, verbose_name="Symbole devise (legacy)"
            ),
        ),
        migrations.AddField(
            model_name="churchextension",
            name="usd_exchange_rate_legacy",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="1 unité de la devise locale équivaut à X dollars USD",
                max_digits=14,
                verbose_name="Taux de change (→ USD) (legacy)",
            ),
        ),
        migrations.RunPython(backup_legacy_data, migrations.RunPython.noop),
        # D'abord modifier le champ currency pour permettre NULL
        migrations.AlterField(
            model_name="churchextension",
            name="currency",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                verbose_name="Code devise"
            ),
        ),
        migrations.RunPython(clear_currency_field, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="churchextension",
            name="currency_symbol",
        ),
        migrations.RemoveField(
            model_name="churchextension",
            name="usd_exchange_rate",
        ),
        migrations.AlterField(
            model_name="churchextension",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="extensions",
                to="churches.currency",
                verbose_name="Devise par défaut",
            ),
        ),
        migrations.RunPython(restore_currency_foreign_key, migrations.RunPython.noop),
    ]
