# Generated by Django 5.2.15 on 2026-06-24 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churches", "0002_alter_appsetting_options_and_more"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newconvert",
            options={
                "verbose_name": "Nouveau converti",
                "verbose_name_plural": "Nouveaux convertis",
            },
        ),
        migrations.AlterModelOptions(
            name="servicereport",
            options={
                "ordering": ["-service_date", "-created_at"],
                "verbose_name": "Rapport de culte",
                "verbose_name_plural": "Rapports de culte",
            },
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="expenses",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="extra_income",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="men_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="visitors_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="women_count",
        ),
        migrations.AddField(
            model_name="servicereport",
            name="brothers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Frères"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="interpreter",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Interprète"
            ),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="maman_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Mamans"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="moderator",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Modérateur"
            ),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="papa_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Papas"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="scripture_text",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Textes bibliques"
            ),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="service_time_end",
            field=models.TimeField(blank=True, null=True, verbose_name="Heure de fin"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="service_time_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Heure de début"
            ),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="sisters_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Sœurs"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="total_expenses",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Total dépenses",
            ),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="total_extra_income",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Total recettes supplémentaires",
            ),
        ),
        migrations.AlterField(
            model_name="newconvert",
            name="address",
            field=models.CharField(blank=True, max_length=220, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="newconvert",
            name="follow_up_owner",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Responsable de suivi"
            ),
        ),
        migrations.AlterField(
            model_name="newconvert",
            name="full_name",
            field=models.CharField(max_length=160, verbose_name="Nom complet"),
        ),
        migrations.AlterField(
            model_name="newconvert",
            name="phone",
            field=models.CharField(blank=True, max_length=60, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="newconvert",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="new_converts",
                to="reports.servicereport",
                verbose_name="Rapport",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="children_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Enfants"),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="extension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="churches.churchextension",
                verbose_name="Extension",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="net_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Solde net / Reste final",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes pastorales"),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="offering_preacher",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Offrandes pour l'orateur",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="offering_regular",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Offrandes ordinaires",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="offering_thanksgiving",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Actions de grâce",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="offering_tithe",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Dîmes"
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="preacher",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Prédicateur"
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="service_date",
            field=models.DateField(verbose_name="Date du culte"),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("sunday", "Culte dominical"),
                    ("week", "Culte de semaine"),
                    ("special", "Culte spécial"),
                ],
                default="sunday",
                max_length=20,
                verbose_name="Type de culte",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="social_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Prélèvement fonds social",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Soumis par",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="theme",
            field=models.CharField(blank=True, max_length=220, verbose_name="Thème"),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="tithe_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Prélèvement dîmes",
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="total_attendance",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Présence totale"
            ),
        ),
        migrations.AlterField(
            model_name="servicereport",
            name="total_offerings",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Total offrandes (brut)",
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="N°")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                ("reason", models.CharField(max_length=300, verbose_name="Motif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_items",
                        to="reports.servicereport",
                        verbose_name="Rapport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="ExtraIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="N°")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_income_items",
                        to="reports.servicereport",
                        verbose_name="Rapport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recette supplémentaire",
                "verbose_name_plural": "Recettes supplémentaires",
                "ordering": ["number"],
            },
        ),
    ]
