# Generated by Django 5.2.17 on 2026-09-14 09:44

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_financial_integrity'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereport',
            name='calculation_version',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='currency',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='social_percentage_applied',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='extra_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='offering_preacher',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='offering_regular',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='offering_thanksgiving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='offering_tithe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='servicereport',
            constraint=models.CheckConstraint(condition=models.Q(('expenses__gte', 0), ('extra_income__gte', 0), ('offering_preacher__gte', 0), ('offering_regular__gte', 0), ('offering_thanksgiving__gte', 0), ('offering_tithe__gte', 0)), name='report_inputs_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='servicereport',
            constraint=models.CheckConstraint(condition=models.Q(('social_percentage_applied__isnull', True), models.Q(('social_percentage_applied__gte', 0), ('social_percentage_applied__lte', 90)), _connector='OR'), name='report_social_percentage_valid'),
        ),
    ]
