# Generated by Django 5.2.15 on 2026-06-24 20:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churches", "0002_alter_appsetting_options_and_more"),
        (
            "reports",
            "0002_alter_newconvert_options_alter_servicereport_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extraincome",
            options={
                "ordering": ["-income_date", "-created_at"],
                "verbose_name": "Recette supplémentaire",
                "verbose_name_plural": "Recettes supplémentaires",
            },
        ),
        migrations.RemoveField(
            model_name="extraincome",
            name="number",
        ),
        migrations.RemoveField(
            model_name="extraincome",
            name="report",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="total_extra_income",
        ),
        migrations.AddField(
            model_name="extraincome",
            name="extension",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_incomes",
                to="churches.churchextension",
                verbose_name="Extension",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extraincome",
            name="income_date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 6, 24, 20, 53, 27, 310088, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ExtraExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="Date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                ("description", models.CharField(max_length=300, verbose_name="Motif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_expenses",
                        to="churches.churchextension",
                        verbose_name="Extension",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense supplémentaire",
                "verbose_name_plural": "Dépenses supplémentaires",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Newcomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=160, verbose_name="Nom complet"),
                ),
                (
                    "invited_by",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Invité par"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newcomers",
                        to="reports.servicereport",
                        verbose_name="Rapport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nouveau venu",
                "verbose_name_plural": "Nouveaux venus",
            },
        ),
    ]
