# Generated by Django 5.2.15 on 2026-06-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reports",
            "0003_alter_extraincome_options_remove_extraincome_number_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicereport",
            name="brothers_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="children_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="maman_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="papa_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="sisters_count",
        ),
        migrations.AddField(
            model_name="servicereport",
            name="babies_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Bébés"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="boys_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Garçons"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="girls_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Filles"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="men_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Hommes"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="women_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Femmes"),
        ),
    ]
