# Generated by Django 5.2.15 on 2026-06-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_remove_servicereport_brothers_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicereport",
            name="babies_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="boys_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="girls_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="men_count",
        ),
        migrations.RemoveField(
            model_name="servicereport",
            name="women_count",
        ),
        migrations.AddField(
            model_name="servicereport",
            name="brothers_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Frères"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="children_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Enfants"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="maman_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Maman"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="papa_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Papa"),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="sisters_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Sœurs"),
        ),
    ]
