# Generated by Django 5.2.15 on 2026-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_rename_attendance_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicereport",
            name="social_percentage_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                editable=False,
                max_digits=5,
                verbose_name="Taux fonds social utilisé (%)",
            ),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="tithe_percentage_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                editable=False,
                max_digits=5,
                verbose_name="Taux dîme utilisé (%)",
            ),
        ),
    ]
