# Generated by Django 5.2.15 on 2026-06-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churches", "0004_currency_remove_churchextension_currency_symbol_and_more"),
        ("reports", "0006_servicereport_social_percentage_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extraexpense",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Devise dans laquelle le montant est exprimé",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extra_expenses",
                to="churches.currency",
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="extraincome",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Devise dans laquelle le montant est exprimé",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extra_incomes",
                to="churches.currency",
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="servicereport",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Devise dans laquelle les montants sont exprimés",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_reports",
                to="churches.currency",
                verbose_name="Devise",
            ),
        ),
    ]
