# Generated by Django 5.2.15 on 2026-09-25 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0004_currency_remove_churchextension_currency_symbol_and_more'),
        ('reports', '0007_extraexpense_currency_extraincome_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIncomeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('offering_regular', 'Offrandes ordinaires'), ('offering_preacher', 'Offrandes pour l’orateur'), ('offering_tithe', 'Dîmes'), ('offering_thanksgiving', 'Actions de grâce')], max_length=30, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant reçu')),
                ('exchange_rate', models.DecimalField(decimal_places=12, editable=False, max_digits=24)),
                ('converted_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='churches.currency', verbose_name='Devise reçue')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_lines', to='reports.servicereport')),
            ],
            options={
                'verbose_name': 'Entrée en devise',
                'verbose_name_plural': 'Entrées en devises',
                'ordering': ['pk'],
            },
        ),
    ]
