# Generated by Django 5.2.15 on 2026-09-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
        ('reports', '0008_report_income_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomer',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ministry.person', verbose_name='Personne déjà enregistrée'),
        ),
        migrations.AddField(
            model_name='newconvert',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ministry.person', verbose_name='Personne déjà enregistrée'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='financial_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='financial_version',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='financial_version',
            field=models.PositiveSmallIntegerField(default=2, editable=False),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='thanksgiving_beneficiary',
            field=models.CharField(blank=True, max_length=160, verbose_name='Bénéficiaire des actions de grâce'),
        ),
    ]
