# Generated by Django 5.2.15 on 2026-06-24 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("report_created", "Nouveau rapport"),
                            ("report_weekly", "Récapitulatif hebdomadaire"),
                            ("report_monthly", "Récapitulatif mensuel"),
                            ("system", "Système"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("body", models.TextField(verbose_name="Message")),
                (
                    "link",
                    models.CharField(blank=True, max_length=300, verbose_name="Lien"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
